### ISSUE TITLE
Cant Create venv

### ISSUE THREAD

**Issue by sakiresy** [YarmolenkoD/notpixel#100]
![vaizdas_2024-10-28_221814846](https://github.com/user-attachments/assets/7f1bdd92-fd87-433e-9887-73e22c911ea8)
It fails when i try to create venv and install requirements.
Python version 3.10
Clean install

**Comment by MaddFun** [comment]
Similarly, the bot is not installed. Python 3.11.2

ERROR: Cannot install -r requirements.txt (line 25), TgCrypto==1.2.5 and tgsessionsconverter==0.0.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested TgCrypto==1.2.5
    opentele 1.15.1 depends on tgcrypto
    tgsessionsconverter 0.0.5 depends on tgcrypto==1.2.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by RecursionHs** [comment]
me too,😊, the author's reliance on external files is too casual. You can generate them yourself, for instance.
```shell
pip install pipreqs
pipreqs . --force
```

or use my `requirements.txt`
```shell
aiocfscrape==1.0.0
aiohttp==3.9.3
aiohttp_proxy==0.1.2
better_proxy==1.2.0
Brotli==1.1.0
cloudscraper==1.2.71
loguru==0.7.2
Pillow==11.0.0
pydantic_settings==2.6.0
Pyrogram==2.0.106
python_dateutil==2.9.0.post0
websockets==12.0
```

**Comment by YarmolenkoD** [comment]
@RecursionHs @sakiresy @MaddFun Hey guys, thanks! Will check it

**Comment by YarmolenkoD** [comment]
@RecursionHs @sakiresy @MaddFun Fixed. Please check it.
